markdown: rdiscount
permalink: /posts/:title
rdiscount:
  extensions: [smart]

gems:
  - jekyll-sitemap

name: Katie Ball
url: http://roachhd.github.io/blog
description: A fantastic blog that is fantastic.
twitter: mektball
